---
# Users should edit this file
# Format of this file http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data


# Password for user pi
PI_USER_PASSWORD: "raspberry"

# Keyboard layout
RASPIAN_KEYBOARD_LAYOUT: "us"

# WIFI
RASPBIAN_OVERRIDE_WIFI_SETTINGS: false
RASPBIAN_WIFI_SSID: "MelbPC-NUE"
RASPBIAN_WIFI_PASSWORD: "peachspeak38"

# Bluetooth LE
RASPBIAN_ENABLE_BLUETOOTH: true

# raspi-config interface settings
RASPICONFIG_ENABLE_SERIAL: true
RASPICONFIG_ENABLE_CAMERA: false
RASPICONFIG_ENABLE_VNC: true
RASPICONFIG_ENABLE_SPI: false
RASPICONFIG_ENABLE_I2C: false
RASPICONFIG_ENABLE_ONEWIRE: false
RASPICONFIG_ENABLE_RGPIO: false

# apt-get install software packages
RASPBIAN_APT_INSTALL:
  - audacity
  - vlc
  - camorama
  - nginx

# install node-red modules
NODERED_MODULES: 
  - node-red-dashboard
  - node-red-node-arduino
  - node-red-contrib-sms-telstra
  - node-red-contrib-influxdb

# Python
PYTHON_INSTALL_MODULES: true

# Python 2 modules available via apt-get install
PYTHON2_APT_MODULES:
  - python-easygui
  - python-bottle
  - python-dev

# Python 2 modules via pip
PYTHON2_PIP_MODULES:
  - pip
  - setuptools
  - matplotlib

# Python 3 modules available via apt-get
PYTHON3_APT_MODULES:
  - python3-dev

# Python 3 modules via pip
PYTHON3_PIP_MODULES:
  - pip
  - setuptools








